### ISSUE TITLE
Consistent wording, renaming of project

### ISSUE THREAD

**Issue by Lukas0907** [PyFeeds/PyFeeds#156]
I propose to rename the project to "pyfeeds" for the following reasons:

1. The project name "feeds" is already taken on pypi.
2. Googling for "feeds" will not realistically lead to this project.
3. pyfeeds is already used as a project name for the documentation hosted at the readthedocs.
4. The "py" prefix indicates that the project uses Python. While this is not really important if one only wants to run existing spiders, it is of bigger importance if one wants to write a new spider.

One downside, however, is that there is a project called "pyfeed" (singular) [1].

Furthermore, I opt for using the term "RSS feed" instead of "Atom feed" or simply "feed" and only referring to Atom in technical contexts where the distinction is actually important. The reasoning behind this is that while Atom and RSS are technically different, the difference is abstracted away by consuming clients and hence doesn't matter for an ordinary user. RSS is a widely recognized term.

[1] http://home.avvanta.com/~steveha/pyfeed.html

**Comment by nblock** [comment]
I moved the project from nblock/feeds to PyFeeds/PyFeeds for now.

**Comment by nblock** [comment]
Done with https://github.com/PyFeeds/PyFeeds/pull/218
