### ISSUE TITLE
ORF TVThek 401

### ISSUE THREAD

**Issue by alexrashed** [PyFeeds/PyFeeds#227]
Hi there!

It looks like the current credentials for the TVthek scraper don't work anymore (401).
I confirmed that by using the hardcoded credentials on https://api-tvthek.orf.at/api/.
With a quick decompile I couldn't find any new basic auth creds (it seems to be highly obfuscated and I haven't had enough time yet).
The TVThek Kodi plugin is facing the same issues: https://github.com/s0faking/plugin.video.orftvthek/issues/109

**Comment by Lukas0907** [comment]
Fixed, thanks!
