### ISSUE TITLE
Handling of relative paths

### ISSUE THREAD

**Issue by Lukas0907** [PyFeeds/PyFeeds#84]
Two paths can be configured:

* cache_dir
* output_path

If the output_path is relative, it is interpreted relative to the directory where the feeds source files are. This is not really practical once feeds is installed via pip and no files should be written to the source directory. Instead the path should be interpreted relative to the directory where feeds is executed.

**Comment by nblock** [comment]
Fixed via https://github.com/PyFeeds/PyFeeds/commit/cb1eb8b264105c915df9b40aa50647867f000f76 and https://github.com/PyFeeds/PyFeeds/commit/d2f684c569e739283f684e561cdfb14d316ae866
